2016-01-26 09:20:50 ERROR [http-bio-10008-exec-4] org.bi.platform.service.resmanage.module.DataModule.queryColumnDataList(DataModule.java:4789) - 数据生成后查看列表获取失败:org.postgresql.util.PSQLException: ERROR: permission denied for relation t13299
2016-01-26 09:21:29 ERROR [http-bio-10008-exec-6] org.bi.platform.service.resmanage.module.DataModule.queryColumnDataList(DataModule.java:4789) - 数据生成后查看列表获取失败:org.postgresql.util.PSQLException: ERROR: permission denied for relation t13299
2016-01-26 11:44:35 ERROR [pool-3-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.updateAPPServerId (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 update bi.app_manage_server set server_id='30BD8705C66848A8B33CEDEE34BC8417',register_time='2016-01-26 11:44:10',task_run_num=0 where server_ip='192.168.11.5' and server_port='1024' was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 update bi.app_manage_server set server_id='30BD8705C66848A8B33CEDEE34BC8417',register_time='2016-01-26 11:44:10',task_run_num=0 where server_ip='192.168.11.5' and server_port='1024' was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 update bi.app_manage_server set server_id='30BD8705C66848A8B33CEDEE34BC8417',register_time='2016-01-26 11:44:10',task_run_num=0 where server_ip='192.168.11.5' and server_port='1024' was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.update(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:254)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:230)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:173)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:71)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:209)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-01-26 11:48:54 ERROR [pool-3-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.updateAPPServerId (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 update bi.app_manage_server set server_id='30BD8705C66848A8B33CEDEE34BC8417',register_time='2016-01-26 11:48:29',task_run_num=0 where server_ip='192.168.11.5' and server_port='1024' was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 update bi.app_manage_server set server_id='30BD8705C66848A8B33CEDEE34BC8417',register_time='2016-01-26 11:48:29',task_run_num=0 where server_ip='192.168.11.5' and server_port='1024' was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 update bi.app_manage_server set server_id='30BD8705C66848A8B33CEDEE34BC8417',register_time='2016-01-26 11:48:29',task_run_num=0 where server_ip='192.168.11.5' and server_port='1024' was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.update(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:254)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:230)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:173)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:71)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:209)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-01-26 12:48:35 ERROR [pool-3-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.updateAPPServerId (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 update bi.app_manage_server set server_id='30BD8705C66848A8B33CEDEE34BC8417',register_time='2016-01-26 12:48:10',task_run_num=0 where server_ip='192.168.11.5' and server_port='1024' was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 update bi.app_manage_server set server_id='30BD8705C66848A8B33CEDEE34BC8417',register_time='2016-01-26 12:48:10',task_run_num=0 where server_ip='192.168.11.5' and server_port='1024' was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 update bi.app_manage_server set server_id='30BD8705C66848A8B33CEDEE34BC8417',register_time='2016-01-26 12:48:10',task_run_num=0 where server_ip='192.168.11.5' and server_port='1024' was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.update(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:254)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:230)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:173)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:71)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:209)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-01-26 12:54:35 ERROR [pool-3-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.updateAPPServerId (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 update bi.app_manage_server set server_id='30BD8705C66848A8B33CEDEE34BC8417',register_time='2016-01-26 12:54:10',task_run_num=0 where server_ip='192.168.11.5' and server_port='1024' was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 update bi.app_manage_server set server_id='30BD8705C66848A8B33CEDEE34BC8417',register_time='2016-01-26 12:54:10',task_run_num=0 where server_ip='192.168.11.5' and server_port='1024' was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 update bi.app_manage_server set server_id='30BD8705C66848A8B33CEDEE34BC8417',register_time='2016-01-26 12:54:10',task_run_num=0 where server_ip='192.168.11.5' and server_port='1024' was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.update(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:254)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:230)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:173)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:71)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:209)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-01-26 14:13:56 ERROR [http-bio-10008-exec-8] org.bi.platform.service.resmanage.module.DataModule.queryColumnDataList(DataModule.java:4793) - 数据生成后查看列表获取失败:org.postgresql.util.PSQLException: ERROR: permission denied for relation t13299
2016-01-26 16:51:49 ERROR [http-bio-10008-exec-9] org.bi.platform.service.resmanage.module.DataLinkModule.getResultList(DataLinkModule.java:743) - org.postgresql.util.PSQLException: ERROR: column t13307.a1056823 does not exist
  Position: 78
2016-01-26 16:58:45 ERROR [http-bio-10008-exec-4] org.bi.platform.service.resmanage.module.DataLinkModule.getResultList(DataLinkModule.java:743) - org.postgresql.util.PSQLException: ERROR: column t13307.a1056823 does not exist
  Position: 78
2016-01-26 17:01:28 ERROR [http-bio-10008-exec-4] org.bi.platform.service.resmanage.module.DataLinkModule.getResultList(DataLinkModule.java:743) - org.postgresql.util.PSQLException: ERROR: column t13307.a1056823 does not exist
  Position: 78
2016-01-26 17:05:19 ERROR [http-bio-10008-exec-6] org.bi.platform.service.resmanage.module.DataLinkModule.getResultList(DataLinkModule.java:743) - org.postgresql.util.PSQLException: ERROR: column t13307.a1056823 does not exist
  Position: 78
2016-01-26 17:05:19 ERROR [http-bio-10008-exec-2] org.bi.platform.service.resmanage.module.DataLinkModule.getResultList(DataLinkModule.java:743) - org.postgresql.util.PSQLException: ERROR: column t13307.a1056823 does not exist
  Position: 78
2016-01-26 21:10:07 ERROR [http-bio-10008-exec-8] org.bi.platform.service.resmanage.module.DataLinkModule.getResultList(DataLinkModule.java:743) - org.postgresql.util.PSQLException: ERROR: column t13332.a1056821 does not exist
  Position: 46
