2016-01-19 10:29:58 ERROR [Thread-18] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:29:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:29:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:29:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:30:58 ERROR [Thread-22] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:30:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:30:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:30:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:31:58 ERROR [Thread-24] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:31:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:31:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:31:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:32:58 ERROR [Thread-26] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:32:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:32:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:32:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:33:58 ERROR [Thread-28] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:33:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:33:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:33:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:34:58 ERROR [Thread-30] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:34:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:34:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:34:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:35:58 ERROR [Thread-32] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:35:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:35:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:35:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:36:58 ERROR [Thread-34] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:36:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:36:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:36:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:37:58 ERROR [Thread-36] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:37:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:37:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:37:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:38:58 ERROR [Thread-38] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:38:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:38:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:38:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:39:58 ERROR [Thread-40] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:39:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:39:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:39:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:40:58 ERROR [Thread-42] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:40:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:40:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:40:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:41:58 ERROR [Thread-44] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:41:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:41:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:41:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:42:58 ERROR [Thread-46] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:42:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:42:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:42:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:43:58 ERROR [Thread-48] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:43:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:43:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:43:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:44:58 ERROR [Thread-50] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:44:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:44:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:44:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:45:58 ERROR [Thread-52] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:45:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:45:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:45:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:46:58 ERROR [Thread-54] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:46:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:46:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:46:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:47:58 ERROR [Thread-56] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:47:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:47:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:47:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:48:58 ERROR [Thread-58] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:48:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:48:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:48:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:49:58 ERROR [Thread-60] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:49:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:49:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:49:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:50:58 ERROR [Thread-62] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:50:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:50:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:50:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:51:58 ERROR [Thread-64] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:51:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:51:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:51:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:52:58 ERROR [Thread-66] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:52:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:52:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:52:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:53:58 ERROR [Thread-68] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:53:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:53:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:53:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:54:58 ERROR [Thread-70] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:54:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:54:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:54:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:55:58 ERROR [Thread-72] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:55:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:55:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:55:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:56:58 ERROR [Thread-74] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:56:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:56:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:56:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:57:58 ERROR [Thread-76] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:57:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:57:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:57:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 10:58:58 ERROR [Thread-78] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataAccessResourceFailureException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:58:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:58:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('2BC643CC84124EDCB1FDCB270459CEDE','192.168.11.5','1024','2016-01-19 10:58:33',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 12:22:28 ERROR [Thread-13] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DuplicateKeyException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('94D36BD9C3AF48C484AA78B4921598AB','192.168.11.5','1024','2016-01-19 12:22:28',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; ERROR: duplicate key value violates unique constraint "pk_app_manage_server"
  Detail: Key (server_id)=(94D36BD9C3AF48C484AA78B4921598AB) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_app_manage_server"
  Detail: Key (server_id)=(94D36BD9C3AF48C484AA78B4921598AB) already exists.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:245)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:192)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 12:23:37 ERROR [Thread-14] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DuplicateKeyException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('94D36BD9C3AF48C484AA78B4921598AB','192.168.11.5','1024','2016-01-19 12:23:37',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; ERROR: duplicate key value violates unique constraint "pk_app_manage_server"
  Detail: Key (server_id)=(94D36BD9C3AF48C484AA78B4921598AB) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_app_manage_server"
  Detail: Key (server_id)=(94D36BD9C3AF48C484AA78B4921598AB) already exists.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:245)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:192)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 12:29:08 ERROR [Thread-14] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DuplicateKeyException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('94D36BD9C3AF48C484AA78B4921598AB','192.168.11.5','1024','2016-01-19 12:29:08',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; ERROR: duplicate key value violates unique constraint "pk_app_manage_server"
  Detail: Key (server_id)=(94D36BD9C3AF48C484AA78B4921598AB) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_app_manage_server"
  Detail: Key (server_id)=(94D36BD9C3AF48C484AA78B4921598AB) already exists.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:245)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:192)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 12:34:12 ERROR [Thread-14] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DuplicateKeyException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('94D36BD9C3AF48C484AA78B4921598AB','192.168.11.5','1024','2016-01-19 12:34:12',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; ERROR: duplicate key value violates unique constraint "pk_app_manage_server"
  Detail: Key (server_id)=(94D36BD9C3AF48C484AA78B4921598AB) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_app_manage_server"
  Detail: Key (server_id)=(94D36BD9C3AF48C484AA78B4921598AB) already exists.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:245)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:192)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 12:48:29 ERROR [Thread-14] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DuplicateKeyException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,server_ip,server_port,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status,order_id)
		values('94D36BD9C3AF48C484AA78B4921598AB','192.168.11.5','1024','2016-01-19 12:48:29',50,0,0,0,'1','1',1) was aborted.  Call getNextException to see the cause.
; SQL []; ERROR: duplicate key value violates unique constraint "pk_app_manage_server"
  Detail: Key (server_id)=(94D36BD9C3AF48C484AA78B4921598AB) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_app_manage_server"
  Detail: Key (server_id)=(94D36BD9C3AF48C484AA78B4921598AB) already exists.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:245)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:192)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:144)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:56)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 12:58:43 ERROR [Thread-14] org.apache.log4j.Logger.error(Logger.java:249) - org.quartz.SchedulerException: Scheduler with name 'DefaultQuartzScheduler' already exists.
ExceptionStackTrace: ---------------start------------------------
	org.quartz.impl.SchedulerRepository.bind(SchedulerRepository.java:80)
	org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1352)
	org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1519)
	org.bi.manage.app.dispatch.APPMonitor.startJob(APPMonitor.java:116)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:234)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:169)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:71)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 14:53:31 ERROR [http-bio-10008-exec-2] org.apache.log4j.Logger.error(Logger.java:249) - org.postgresql.util.PSQLException: ERROR: relation "bi.t12824" does not exist
  Position: 85
ExceptionStackTrace: ---------------start------------------------
	org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
	org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
	org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:559)
	org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403)
	org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:283)
	org.bi.platform.service.resmanage.module.DimModule.getDataByDataId(DimModule.java:280)
	org.bi.platform.service.resmanage.module.DimModule$$FastClassBySpringCGLIB$$6d2ee012.invoke(<generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:629)
	org.bi.platform.service.resmanage.module.DimModule$$EnhancerBySpringCGLIB$$22444772.getDataByDataId(<generated>)
	org.bi.platform.service.resmanage.controller.DimController.getDataByDataId(DimController.java:195)
	org.bi.platform.service.resmanage.controller.DimController$$FastClassBySpringCGLIB$$154d3372.invoke(<generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:629)
	org.bi.platform.service.resmanage.controller.DimController$$EnhancerBySpringCGLIB$$7a7a8ed2.getDataByDataId(<generated>)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	java.lang.reflect.Method.invoke(Method.java:597)
	org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:686)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	com.radiadesign.catalina.session.RedisSessionHandlerValve.invoke(RedisSessionHandlerValve.java:26)
	org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 14:53:31 ERROR [http-bio-10008-exec-2] org.apache.log4j.Logger.error(Logger.java:249) - java.lang.Exception: org.postgresql.util.PSQLException: ERROR: relation "bi.t12824" does not exist
  Position: 85
ExceptionStackTrace: ---------------start------------------------
	org.bi.platform.service.resmanage.module.DimModule.getDataByDataId(DimModule.java:307)
	org.bi.platform.service.resmanage.module.DimModule$$FastClassBySpringCGLIB$$6d2ee012.invoke(<generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:629)
	org.bi.platform.service.resmanage.module.DimModule$$EnhancerBySpringCGLIB$$22444772.getDataByDataId(<generated>)
	org.bi.platform.service.resmanage.controller.DimController.getDataByDataId(DimController.java:195)
	org.bi.platform.service.resmanage.controller.DimController$$FastClassBySpringCGLIB$$154d3372.invoke(<generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:629)
	org.bi.platform.service.resmanage.controller.DimController$$EnhancerBySpringCGLIB$$7a7a8ed2.getDataByDataId(<generated>)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	java.lang.reflect.Method.invoke(Method.java:597)
	org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:686)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	com.radiadesign.catalina.session.RedisSessionHandlerValve.invoke(RedisSessionHandlerValve.java:26)
	org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 14:53:36 ERROR [http-bio-10008-exec-3] org.apache.log4j.Logger.error(Logger.java:249) - org.postgresql.util.PSQLException: ERROR: relation "bi.t12878" does not exist
  Position: 67
ExceptionStackTrace: ---------------start------------------------
	org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
	org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
	org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:559)
	org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403)
	org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:283)
	org.bi.platform.service.resmanage.module.DimModule.getDataByDataId(DimModule.java:280)
	org.bi.platform.service.resmanage.module.DimModule$$FastClassBySpringCGLIB$$6d2ee012.invoke(<generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:629)
	org.bi.platform.service.resmanage.module.DimModule$$EnhancerBySpringCGLIB$$22444772.getDataByDataId(<generated>)
	org.bi.platform.service.resmanage.controller.DimController.getDataByDataId(DimController.java:195)
	org.bi.platform.service.resmanage.controller.DimController$$FastClassBySpringCGLIB$$154d3372.invoke(<generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:629)
	org.bi.platform.service.resmanage.controller.DimController$$EnhancerBySpringCGLIB$$7a7a8ed2.getDataByDataId(<generated>)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	java.lang.reflect.Method.invoke(Method.java:597)
	org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:686)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	com.radiadesign.catalina.session.RedisSessionHandlerValve.invoke(RedisSessionHandlerValve.java:26)
	org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 14:53:36 ERROR [http-bio-10008-exec-3] org.apache.log4j.Logger.error(Logger.java:249) - java.lang.Exception: org.postgresql.util.PSQLException: ERROR: relation "bi.t12878" does not exist
  Position: 67
ExceptionStackTrace: ---------------start------------------------
	org.bi.platform.service.resmanage.module.DimModule.getDataByDataId(DimModule.java:307)
	org.bi.platform.service.resmanage.module.DimModule$$FastClassBySpringCGLIB$$6d2ee012.invoke(<generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:629)
	org.bi.platform.service.resmanage.module.DimModule$$EnhancerBySpringCGLIB$$22444772.getDataByDataId(<generated>)
	org.bi.platform.service.resmanage.controller.DimController.getDataByDataId(DimController.java:195)
	org.bi.platform.service.resmanage.controller.DimController$$FastClassBySpringCGLIB$$154d3372.invoke(<generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:629)
	org.bi.platform.service.resmanage.controller.DimController$$EnhancerBySpringCGLIB$$7a7a8ed2.getDataByDataId(<generated>)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	java.lang.reflect.Method.invoke(Method.java:597)
	org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:686)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	com.radiadesign.catalina.session.RedisSessionHandlerValve.invoke(RedisSessionHandlerValve.java:26)
	org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 18:52:15 ERROR [ConsumerFetcherThread-GROUPID0_host-10-1-235-12-1453198110600-16ad16cd-0-12] kafka.utils.Logging$class.error(Logging.scala:97) - [ConsumerFetcherThread-GROUPID0_host-10-1-235-12-1453198110600-16ad16cd-0-12], Error for partition [KAFKA_APP_ACK_TOPIC,1] to broker 12:class kafka.common.NotLeaderForPartitionException
2016-01-19 18:58:32 ERROR [DefaultQuartzScheduler_Worker-5] com.alibaba.druid.pool.DruidDataSource.recycle(DruidDataSource.java:1299) - recyle error
org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc2.AbstractJdbc2Connection.checkClosed(AbstractJdbc2Connection.java:822)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.clearWarnings(AbstractJdbc2Connection.java:705)
	at com.alibaba.druid.pool.DruidConnectionHolder.reset(DruidConnectionHolder.java:241)
	at com.alibaba.druid.pool.DruidDataSource.recycle(DruidDataSource.java:1250)
	at com.alibaba.druid.pool.DruidPooledConnection.recycle(DruidPooledConnection.java:292)
	at com.alibaba.druid.pool.DruidPooledConnection.syncClose(DruidPooledConnection.java:271)
	at com.alibaba.druid.pool.DruidPooledConnection.close(DruidPooledConnection.java:228)
	at org.springframework.jdbc.datasource.DataSourceUtils.doCloseConnection(DataSourceUtils.java:341)
	at org.springframework.jdbc.datasource.DataSourceUtils.doReleaseConnection(DataSourceUtils.java:328)
	at org.springframework.jdbc.datasource.DataSourceUtils.releaseConnection(DataSourceUtils.java:294)
	at org.mybatis.spring.transaction.SpringManagedTransaction.close(SpringManagedTransaction.java:123)
	at org.apache.ibatis.executor.BaseExecutor.close(BaseExecutor.java:85)
	at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at $Proxy23.close(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.close(DefaultSqlSession.java:203)
	at org.mybatis.spring.SqlSessionUtils.closeSqlSession(SqlSessionUtils.java:170)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:369)
	at $Proxy9.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:198)
	at org.bi.manage.app.job.TableImportJob.execute(TableImportJob.java:40)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2016-01-19 18:58:32 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:32 ERROR [DefaultQuartzScheduler_Worker-5] org.apache.log4j.Logger.error(Logger.java:261) - TableImportJob出现异常：org.springframework.dao.DataAccessResourceFailureException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: FATAL: terminating connection due to administrator command
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### Cause: org.postgresql.util.PSQLException: FATAL: terminating connection due to administrator command
; SQL []; FATAL: terminating connection due to administrator command; nested exception is org.postgresql.util.PSQLException: FATAL: terminating connection due to administrator command
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.selectList(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:198)
	org.bi.manage.app.job.TableImportJob.execute(TableImportJob.java:40)
	org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 18:58:33 ERROR [DefaultQuartzScheduler_Worker-6] com.alibaba.druid.pool.DruidDataSource.recycle(DruidDataSource.java:1299) - recyle error
org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc2.AbstractJdbc2Connection.checkClosed(AbstractJdbc2Connection.java:822)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.clearWarnings(AbstractJdbc2Connection.java:705)
	at com.alibaba.druid.pool.DruidConnectionHolder.reset(DruidConnectionHolder.java:241)
	at com.alibaba.druid.pool.DruidDataSource.recycle(DruidDataSource.java:1250)
	at com.alibaba.druid.pool.DruidPooledConnection.recycle(DruidPooledConnection.java:292)
	at com.alibaba.druid.pool.DruidPooledConnection.syncClose(DruidPooledConnection.java:271)
	at com.alibaba.druid.pool.DruidPooledConnection.close(DruidPooledConnection.java:228)
	at org.springframework.jdbc.datasource.DataSourceUtils.doCloseConnection(DataSourceUtils.java:341)
	at org.springframework.jdbc.datasource.DataSourceUtils.doReleaseConnection(DataSourceUtils.java:328)
	at org.springframework.jdbc.datasource.DataSourceUtils.releaseConnection(DataSourceUtils.java:294)
	at org.mybatis.spring.transaction.SpringManagedTransaction.close(SpringManagedTransaction.java:123)
	at org.apache.ibatis.executor.BaseExecutor.close(BaseExecutor.java:85)
	at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at $Proxy23.close(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.close(DefaultSqlSession.java:203)
	at org.mybatis.spring.SqlSessionUtils.closeSqlSession(SqlSessionUtils.java:170)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:369)
	at $Proxy9.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:198)
	at org.bi.manage.app.job.PriodTableImportJob.execute(PriodTableImportJob.java:41)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2016-01-19 18:58:33 ERROR [DefaultQuartzScheduler_Worker-6] org.apache.log4j.Logger.error(Logger.java:261) - PriodTableImportJob出现异常：org.springframework.dao.DataAccessResourceFailureException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: FATAL: terminating connection due to administrator command
### The error may involve AppConfigDataMapper.selectImportTable-Inline
### The error occurred while setting parameters
### Cause: org.postgresql.util.PSQLException: FATAL: terminating connection due to administrator command
; SQL []; FATAL: terminating connection due to administrator command; nested exception is org.postgresql.util.PSQLException: FATAL: terminating connection due to administrator command
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:103)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.selectList(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:198)
	org.bi.manage.app.job.PriodTableImportJob.execute(PriodTableImportJob.java:41)
	org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
ExceptionStackTrace: ---------------end------------------------

2016-01-19 18:58:33 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:58:34 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 18:59:04 ERROR [Druid-ConnectionPool-Create-1128039744] com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1890) - create connection error, url: jdbc:postgresql://10.1.235.12:5432/saasbi01
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1375)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1431)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1888)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at org.postgresql.core.PGStream.<init>(PGStream.java:60)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:101)
	... 11 more
2016-01-19 19:43:22 ERROR [Thread-16] org.apache.log4j.Logger.error(Logger.java:249) - java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
ExceptionStackTrace: ---------------start------------------------
	java.util.ArrayList.RangeCheck(ArrayList.java:547)
	java.util.ArrayList.remove(ArrayList.java:387)
	org.bi.webbace.util.VisitLoggerUtil$VisitLogThread.run(VisitLoggerUtil.java:154)
ExceptionStackTrace: ---------------end------------------------

